export { default as Welcome } from './Welcome/index';
export { default as Jumbotron } from './Jumbotron/index';
export { default as Footer } from './Footer/index';
export { default as Optform } from './Optform/index';
export { default as Header } from './Header/index';
export { default as Feature } from './Features/index';
export { default as Form } from './Form/index';
export { default as Profiles } from './Profiles/index';
export { default as Loading } from './Loading/index';
